<?xml version="1.0"?>
<robot name="myturtle" xmlns:xacro="httpL//ros.org/wiki/xacro">
  <!-- <xacro:include name="$(find myturtle_gazebo)/rviz/urdf.rviz"/> -->
  <xacro:include filename="$(find myturtle_description)/urdf/myturtle_base_gazebo.urdf.xacro"/>

  <!-- <xacro:property name="" value=""/> -->
  <xacro:property name="M_PI" value="3.1415926535897931"/>

  <xacro:property name="base_collision_height" value="0.1"/>
  <xacro:property name="base_collision_radius" value="0.15"/>
  <xacro:property name="wheel_thickness" value="0.01"/> <!-- 1 cm = 0.01 m -->
  <xacro:property name="wheel_radius" value="0.045"/> <!-- diameter = 9 cm -->
  <xacro:property name="wheels_distance" value="0.2644"/>
  <xacro:property name="wheel_center_offset" value="-0.0278"/> <!-- where center of the motor locate at relative to the base plate -->
  <xacro:property name="caster_wheels_distance" value="0.25"/>
  <xacro:property name="caster_wheel_length" value="0.02"/>
  <xacro:property name="caster_wheel_radius" value="0.01"/>
  <xacro:property name="base_offset_from_ground" value="${wheel_radius - wheel_center_offset}"/>
  <xacro:property name="caster_wheel_center_offset" value="-${base_offset_from_ground + (base_collision_height/2) - caster_wheel_radius}"/>

  <link name="base_footprint"/>
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_collision_height}" radius="${base_collision_radius}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${base_collision_height}" radius="${base_collision_radius}"/>
      </geometry>
    </collision>

    <inertial>
        <!-- COM experimentally determined -->
        <origin xyz="0.01 0 0"/>
        <mass value="2.4"/> <!-- 2.4/2.6 kg for small/big battery pack -->
        <!-- Kobuki's inertia tensor is approximated by a cylinder with homogeneous mass distribution
             More details: http://en.wikipedia.org/wiki/List_of_moment_of_inertia_tensors
             m = 2.4 kg; h = 0.09 m; r = 0.175 m
             ixx = 1/12 * m * (3 * r^2 + h^2)
             iyy = 1/12 * m * (3 * r^2 + h^2)
             izz = 1/2 * m * r^2
          -->
        <inertia ixx="0.019995" ixy="0.0" ixz="0.0"
                 iyy="0.019995" iyz="0.0"
                 izz="0.03675" />
     </inertial>
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_collision_height/2}" rpy="0 0 0"/>
  </joint>


  <link name="left_wheel_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="blue">
        <color rgba="0 0 0.8 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>

    <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.001" />
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0 ${wheels_distance/2} ${wheel_center_offset-base_collision_height/2}" rpy="${M_PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="right_wheel_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="blue">
        <color rgba="0 0 0.8 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>

    <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.001" />
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0 -${wheels_distance/2} ${wheel_center_offset-base_collision_height/2}" rpy="${M_PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="front_caster_wheel_link">
    <visual>
      <geometry>
        <cylinder length="${caster_wheel_length}" radius="${caster_wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="blue">
        <color rgba="0 0 0.8 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${caster_wheel_length}" radius="${caster_wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>

    <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.001" />
    </inertial>
  </link>

  <joint name="front_caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster_wheel_link"/>
    <origin xyz="${caster_wheels_distance/2} 0 ${caster_wheel_center_offset}" rpy="${M_PI/2} 0 0"/>
  </joint>

  <link name="back_caster_wheel_link">
    <visual>
      <geometry>
        <cylinder length="${caster_wheel_length}" radius="${caster_wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="blue">
        <color rgba="0 0 0.8 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${caster_wheel_length}" radius="${caster_wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>

    <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.001" />
    </inertial>
  </link>

  <joint name="back_caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="back_caster_wheel_link"/>
    <origin xyz="-${caster_wheels_distance/2} 0 ${caster_wheel_center_offset}" rpy="${M_PI/2} 0 0"/>
  </joint>










  <!-- Kobuki's sensors -->
    <joint name="gyro_joint" type="fixed">
      <axis xyz="0 1 0"/>
      <origin xyz="0.056 0.062 0.0202" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="gyro_link"/>
    </joint>
    <link name="gyro_link">
      <inertial>
        <mass value="0.001"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0"
                 iyy="0.000001" iyz="0"
                 izz="0.0001"/>
      </inertial>
    </link>

    <joint name="cliff_sensor_left_joint" type="fixed">
      <origin xyz="0.08734 0.13601 0.0214" rpy="0 ${M_PI/2} 0" />
      <parent link="base_link"/>
      <child link="cliff_sensor_left_link" />
    </joint>
    <link name="cliff_sensor_left_link">
      <inertial>
        <mass value="0.0001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001" />
      </inertial>
    </link>

    <joint name="cliff_sensor_right_joint" type="fixed">
      <origin xyz="0.085 -0.13601 0.0214" rpy="0 ${M_PI/2} 0" />
      <parent link="base_link"/>
      <child link="cliff_sensor_right_link" />
    </joint>
    <link name="cliff_sensor_right_link">
      <inertial>
        <mass value="0.0001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001" />
      </inertial>
    </link>

    <joint name="cliff_sensor_front_joint" type="fixed">
      <origin xyz="0.156 0.00 0.0214" rpy="0 ${M_PI/2} 0" />
      <parent link="base_link"/>
      <child link="cliff_sensor_front_link" />
    </joint>
    <link name="cliff_sensor_front_link">
      <inertial>
        <mass value="0.0001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001" />
      </inertial>
    </link>


    <kobuki_sim/>



  <!-- <xacro:include filename="$(find turtlebot_description)/urdf/turtlebot_properties.urdf.xacro"/>
  <xacro:property name="kinect_cam_py" value="-0.0125"/>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${cam_px} ${kinect_cam_py} ${cam_pz}" rpy="${cam_or} ${cam_op} ${cam_oy}"/>
    <parent link="base_link"/>
    <child link="camera_rgb_frame" />
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_joint" type="fixed">
    <origin xyz="-0.031 ${-kinect_cam_py} -0.016" rpy="0 0 0"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <visual>
     <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}"/>
      <geometry>
       <mesh filename="package://turtlebot_description/meshes/sensors/kinect.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="0.07271 0.27794 0.073"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.564" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.003881243" ixy="0.0" ixz="0.0"
               iyy="0.000498940" iyz="0.0"
               izz="0.003879257" />
    </inertial>
  </link> -->
</robot>
